### ISSUE TITLE
T-Eval Conference

### ISSUE THREAD

**Issue by OfficerChul** [quchangle1/LLM-Tool-Survey#10]
Hi, it seems like T-Eval got accepted to ACL, not ICLR.
https://aclanthology.org/2024.acl-long.515.pdf

**Comment by quchangle1** [comment]
Thank you for the clarification! I have made the correction.

**Comment by OfficerChul** [comment]
你的研究非常出色，谢谢你。我是首尔大学的硕士生，你的研究对我帮助很大。

**Comment by quchangle1** [comment]
非常感谢您对我们工作的关注和认可！我是中国人民大学的直博生，希望未来有机会我们可以合作！
