### ISSUE TITLE
中文版本

### ISSUE THREAD

**Issue by tttonytan** [quchangle1/LLM-Tool-Survey#2]
真诚发问作者大大们，有这个survey的中文版嘛

**Comment by KID-22** [comment]
感谢您对我们survey的关注！目前我们还没有中文版的计划，不过我们关注到PaperAgent公众号写了一个关于我们这篇survey的[中文简要介绍](https://mp.weixin.qq.com/s/pPkrHHkmVC29e_c2U8YEGg)，希望对你有帮助~

**Comment by tttonytan** [comment]
感谢

**Comment by quchangle1** [comment]
非常感谢您的关注，我们注意到PaperAgent公众号写了一个关于我们这篇survey的[中文简要](https://mp.weixin.qq.com/s/pPkrHHkmVC29e_c2U8YEGg)介绍以及旺知识公众号写了一个比较[全面的中文介绍](https://mp.weixin.qq.com/s/SnvxsKmkgI_kHvwaLUK-0A)，您可以看下，希望对您有帮助~
