### ISSUE TITLE
框架推荐

### ISSUE THREAD

**Issue by songguorui** [quchangle1/LLM-Tool-Survey#4]
作者可以推荐几个好用的工具调用框架吗，非常感谢

**Comment by quchangle1** [comment]
非常感谢您的关注，您可以关注一些最新论文的baseline，一般常见的有ReAct，DFSDT，以及像RestGPT这种类似multi-agent的框架，具体的方法可以看这几篇相关的论文，希望对您有帮助~

**Comment by songguorui** [comment]
收到，感谢您的回复，学习下！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quchangle1/LLM-Tool-Survey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月5日(星期五) 中午11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quchangle1/LLM-Tool-Survey] 框架推荐 (Issue #4)





 
非常感谢您的关注，您可以关注一些最新论文的baseline，一般常见的有ReAct，DFSDT，以及像RestGPT这种类似multi-agent的框架，具体的方法可以看这几篇相关的论文，希望对您有帮助~
