### ISSUE TITLE
Add Toolshed: Advanced RAG-Tool Fusion to "Tool Selection" Retriever-based and Task

### ISSUE THREAD

**Issue by EliasLumer** [quchangle1/LLM-Tool-Survey#9]
Title:
Toolshed: Scale Tool-Equipped Agents with Advanced RAG-Tool Fusion and Tool Knowledge Bases
Paper Link: https://arxiv.org/abs/2410.14594

===
It's within the tool selection and retriever-based approach. Additionally, add to task planning tuning-free methods if possible, as it states in the paper the approach is to scale tool selection, retrieval, and planning.

**Comment by quchangle1** [comment]
Thanks for your interest in our survey! I've already added Toolshed!  You can find it in the Task Planning and Tool Selection sections.

**Comment by EliasLumer** [comment]
Perfect. Thanks. Can you change/add to retriever-based tool selection,
since it primarily uses a retriever and knowledge base rather than the LLM
to select tools (it uses both but retriever is 80%+).

**Comment by quchangle1** [comment]
Of course! I have changed it.
